dist: bionic

language: rust
rust:
  - stable

cache: cargo

before_script:
  - rustup component add clippy
  - rustup component add rustfmt

script:
  - cargo fmt -- --check
  - cargo clippy -- --deny=clippy::all
  - cargo build --verbose --all
  - cargo test --verbose